### ISSUE TITLE
Want to team up?

### ISSUE THREAD

**Issue by kewisch** [wdzeng/firefox-addon#6]
Hey, I just stumbled upon your action, great work! I have a similar action that covers many of the features you have here plus a few more. Would you be interested in joining forces and focusing on my action? https://github.com/kewisch/action-web-ext

If you are not interested feel free to close the issue, no worries :)

**Comment by wdzeng** [comment]
Hi @kewisch,

Thank you for your kind words and for sharing your action with me! Your action looks great as well, and I appreciate the invitation to collaborate. Unfortunately due to my current workload I may not be active on open-sourced projects or collaborate with other people at this time :( If I find some free time in the future I’d be happy to contribute with some PRs to your project!

**Comment by kewisch** [comment]
Totally understand where you're coming from! I was thinking it might make sense to consolidate some of the submission actions into one well-maintained solution, so users have a single, reliable option to depend on. How would you feel about updating your action with a notice suggesting users switch over to mine? I'd be happy to help with migration documentation to make the transition smooth for everyone. It could streamline things and ensure we’re both contributing to something more sustainable long-term. What do you think?
